openapi: 3.0.0
info:
  title: InfluxDB Cloud API Service Authorizations (API tokens) Authorizations (API tokens) DBRPs API
  version: 2.0.1
  description: 'The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.

    '
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
- url: /api/v2
security:
- TokenAuthentication: []
tags:
- name: DBRPs
  description: 'The InfluxDB 1.x data model includes [databases](https://docs.influxdata.com/influxdb/v1.8/concepts/glossary/#database)

    and [retention policies](https://docs.influxdata.com/influxdb/v1.8/concepts/glossary/#retention-policy-rp).

    InfluxDB 2.x replaces databases and retention policies with buckets.

    To support InfluxDB 1.x query and write patterns in InfluxDB 2.x,

    databases and retention policies are mapped to buckets using the

    database and retention policy (DBRP) mapping service.

    The DBRP mapping service uses the database and retention policy

    specified in 1.x compatibility API requests to route operations to a bucket.


    ### Related guides


    - [Database and retention policy mapping](https://docs.influxdata.com/influxdb/cloud/reference/api/influxdb-1x/dbrp/)

    '
paths:
  /dbrps:
    get:
      operationId: GetDBRPs
      tags:
      - DBRPs
      summary: List database retention policy mappings
      description: 'Lists database retention policy (DBRP) mappings.


        #### Related guide


        - [Database and retention policy mapping](https://docs.influxdata.com/influxdb/cloud/reference/api/influxdb-1x/dbrp/)

        '
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - in: query
        name: orgID
        description: 'An organization ID.

          Only returns DBRP mappings for the specified organization.

          '
        schema:
          type: string
      - in: query
        name: org
        description: 'An organization name.

          Only returns DBRP mappings for the specified organization.

          '
        schema:
          type: string
      - in: query
        name: id
        description: 'A DBPR mapping ID.

          Only returns the specified DBRP mapping.

          '
        schema:
          type: string
      - in: query
        name: bucketID
        description: 'A bucket ID.

          Only returns DBRP mappings that belong to the specified bucket.

          '
        schema:
          type: string
      - in: query
        name: default
        description: Specifies filtering on default
        schema:
          type: boolean
      - in: query
        name: db
        description: 'A database.

          Only returns DBRP mappings that belong to the 1.x database.

          '
        schema:
          type: string
      - in: query
        name: rp
        description: 'A [retention policy](https://docs.influxdata.com/influxdb/v1.8/concepts/glossary/#retention-policy-rp).

          Specifies the 1.x retention policy to filter on.

          '
        schema:
          type: string
      responses:
        '200':
          description: Success. The response body contains a list of database retention policy mappings.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DBRPs'
              examples:
                successResponse:
                  value:
                    content:
                    - id: 0a3cbb5dd526a000
                      database: example_database_1
                      retention_policy: autogen
                      default: true
                      orgID: bea7ea952287f70d
                      bucketID: 4d4d9d5b61dee751
                    - id: 0a3cbcde20e38000
                      database: example_database_2
                      retention_policy: example_retention_policy
                      default: false
                      orgID: bea7ea952287f70d
                      bucketID: 4d4d9d5b61dee751
        '400':
          description: Bad request. The request has one or more invalid parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                invalidRequest:
                  description: 'The query parameters contain invalid values.

                    '
                  value:
                    code: invalid
                    message: invalid ID
        '401':
          $ref: '#/components/responses/AuthorizationError'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      operationId: PostDBRP
      tags:
      - DBRPs
      summary: Add a database retention policy mapping
      description: 'Creates a database retention policy (DBRP) mapping and returns the mapping.


        Use this endpoint to add InfluxDB 1.x API compatibility to your

        InfluxDB Cloud or InfluxDB OSS 2.x buckets. Your buckets must contain a

        DBRP mapping in order to query and write using the InfluxDB 1.x API.

        object.


        #### Related guide


        - [Database and retention policy mapping](https://docs.influxdata.com/influxdb/cloud/reference/api/influxdb-1x/dbrp/)

        '
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      requestBody:
        description: 'The database retention policy mapping to add.


          Note that _`retention_policy`_ is a required parameter in the request body.

          The value of _`retention_policy`_ can be any arbitrary `string` name or

          value, with the default value commonly set as `autogen`.

          The value of _`retention_policy`_ isn''t a [retention_policy](https://docs.influxdata.com/influxdb/cloud/reference/glossary/#retention-policy-rp)

          '
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DBRPCreate'
      responses:
        '201':
          description: Created. The response body contains the database retention policy mapping.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DBRP'
              examples:
                successResponse:
                  value:
                    id: 0a3cbb5dd526a000
                    database: example_database
                    retention_policy: autogen
                    default: true
                    orgID: bea7ea952287f70d
                    bucketID: 4d4d9d5b61dee751
        '400':
          description: Bad request. The mapping in the request has one or more invalid IDs.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                invalidRequest:
                  description: 'The query parameters contain invalid values.

                    '
                  value:
                    code: invalid
                    message: invalid ID
        '401':
          $ref: '#/components/responses/AuthorizationError'
        '404':
          $ref: '#/components/responses/ResourceNotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-codeSamples:
      - lang: Shell
        label: 'cURL: create a database retention policy mapping'
        source: "curl --request POST \\\n   \"http://localhost:8086/api/v2/dbrp/\" \\\n  --header 'Content-type: application/json' \\\n  --header \"Authorization: Token INFLUXDB_TOKEN\" \\\n  --data-binary @- << EOF\n    { \\\n      \"bucketID\": \"INFLUXDB_BUCKET_ID\", \\\n      \"orgID\": \"INFLUXDB_ORG_ID\", \\\n      \"database\": \"database_name\", \\\n      \"default\": true, \\\n      \"retention_policy\": \"example_retention_policy_name\" \\\n    }\nEOF\n"
  /dbrps/{dbrpID}:
    get:
      operationId: GetDBRPsID
      tags:
      - DBRPs
      summary: Retrieve a database retention policy mapping
      description: 'Retrieves the specified retention policy (DBRP) mapping.


        #### Related guide


        - [Database and retention policy mapping](https://docs.influxdata.com/influxdb/cloud/reference/api/influxdb-1x/dbrp/)

        '
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - in: query
        name: orgID
        description: 'An organization ID.

          Specifies the organization that owns the DBRP mapping.

          '
        schema:
          type: string
      - in: query
        name: org
        description: 'An organization name.

          Specifies the organization that owns the DBRP mapping.

          '
        schema:
          type: string
      - in: path
        name: dbrpID
        schema:
          type: string
        required: true
        description: 'A DBRP mapping ID.

          Specifies the DBRP mapping.

          '
      responses:
        '200':
          description: Success. The response body contains the DBRP mapping.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DBRPGet'
              examples:
                successResponse:
                  value:
                    content:
                      id: 0a3cbb5dd526a000
                      database: example_database_1
                      retention_policy: autogen
                      default: true
                      orgID: bea7ea952287f70d
                      bucketID: 4d4d9d5b61dee751
        '400':
          description: Bad Request. Query parameters contain invalid values.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                invalidRequest:
                  description: 'The query parameters contain invalid values.

                    '
                  value:
                    code: invalid
                    message: invalid ID
        '401':
          $ref: '#/components/responses/AuthorizationError'
        '404':
          $ref: '#/components/responses/ResourceNotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      operationId: PatchDBRPID
      tags:
      - DBRPs
      summary: Update a database retention policy mapping
      requestBody:
        description: 'Updates the database retention policy (DBRP) mapping and returns the mapping.


          Use this endpoint to modify the _retention policy_ (`retention_policy` property) of a DBRP mapping.


          #### Related guide


          - [Database and retention policy mapping](https://docs.influxdata.com/influxdb/cloud/reference/api/influxdb-1x/dbrp/)

          '
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DBRPUpdate'
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - in: query
        name: orgID
        description: 'An organization ID.

          Specifies the organization that owns the DBRP mapping.

          '
        schema:
          type: string
      - in: query
        name: org
        description: 'An organization name.

          Specifies the organization that owns the DBRP mapping.

          '
        schema:
          type: string
      - in: path
        name: dbrpID
        schema:
          type: string
        required: true
        description: 'A DBRP mapping ID.

          Specifies the DBRP mapping.

          '
      responses:
        '200':
          description: An updated mapping
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DBRPGet'
              examples:
                successResponse:
                  value:
                    content:
                      id: 0a3cbb5dd526a000
                      database: example_database
                      retention_policy: example_retention_policy
                      default: false
                      orgID: bea7ea952287f70d
                      bucketID: 4d4d9d5b61dee751
        '400':
          description: Bad Request. Query parameters contain invalid values.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                invalidRequest:
                  description: 'The query parameters contain invalid values.

                    '
                  value:
                    code: invalid
                    message: invalid ID
        '401':
          $ref: '#/components/responses/AuthorizationError'
        '404':
          $ref: '#/components/responses/ResourceNotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-codeSamples:
      - lang: Shell
        label: 'cURL: Update a DBRP mapping'
        source: "curl --request PATCH \\\n   \"http://localhost:8086/api/v2/dbrp/DBRP_ID\" \\\n  --header 'Content-type: application/json' \\\n  --header \"Authorization: Token INFLUX_API_TOKEN\" \\\n  --data-binary @- << EOF\n    {\n      \"default\": true,\n      \"retention_policy\": \"example_retention_policy_name\"\n    }\nEOF\n"
    delete:
      operationId: DeleteDBRPID
      tags:
      - DBRPs
      summary: Delete a database retention policy
      description: 'Deletes the specified database retention policy (DBRP) mapping.


        #### Related guide


        - [Database and retention policy mapping](https://docs.influxdata.com/influxdb/cloud/reference/api/influxdb-1x/dbrp/)

        '
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - in: query
        name: orgID
        description: 'An organization ID.

          Specifies the organization that owns the DBRP mapping.

          '
        schema:
          type: string
      - in: query
        name: org
        description: 'An organization name.

          Specifies the organization that owns the DBRP mapping.

          '
        schema:
          type: string
      - in: path
        name: dbrpID
        schema:
          type: string
        required: true
        description: 'A DBRP mapping ID.

          Only returns the specified DBRP mapping.

          '
      responses:
        '204':
          description: Success. The delete is accepted.
        '400':
          description: Bad Request. Query parameters contain invalid values.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                invalidRequest:
                  description: 'The query parameters contain invalid values.

                    '
                  value:
                    code: invalid
                    message: invalid ID
        '401':
          $ref: '#/components/responses/AuthorizationError'
        '404':
          $ref: '#/components/responses/ResourceNotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  responses:
    AuthorizationError:
      description: "Unauthorized. The error may indicate one of the following:\n\n  * The `Authorization: Token` header is missing or malformed.\n  * The API token value is missing from the header.\n  * The token doesn't have sufficient permissions to write to this organization and bucket.\n"
      content:
        application/json:
          schema:
            properties:
              code:
                description: 'The HTTP status code description. Default is `unauthorized`.

                  '
                readOnly: true
                type: string
                enum:
                - unauthorized
              message:
                readOnly: true
                description: A human-readable message that may contain detail about the error.
                type: string
          examples:
            tokenNotAuthorized:
              summary: Token is not authorized to access a resource
              value:
                code: unauthorized
                message: unauthorized access
    ResourceNotFoundError:
      description: "Not found.\nA requested resource was not found.\nThe response body contains the requested resource type and the name value\n(if you passed it)--for example:\n\n- `\"organization name \\\"my-org\\\" not found\"`\n- `\"organization not found\"`: indicates you passed an ID that did not match\n   an organization.\n"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            org-not-found:
              summary: Organization name not found
              value:
                code: not found
                message: organization name "my-org" not found
            bucket-not-found:
              summary: Bucket name not found
              value:
                code: not found
                message: bucket "air_sensor" not found
            orgID-not-found:
              summary: Organization ID not found
              value:
                code: not found
                message: organization not found
    InternalServerError:
      description: 'Internal server error.

        The server encountered an unexpected situation.

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    DBRP:
      type: object
      properties:
        id:
          type: string
          description: 'The resource ID that InfluxDB uses to uniquely identify the database retention policy (DBRP) mapping.

            '
          readOnly: true
        orgID:
          type: string
          description: 'An organization ID.

            Identifies the [organization](https://docs.influxdata.com/influxdb/cloud/reference/glossary/#organization) that owns the mapping.

            '
        bucketID:
          type: string
          description: 'A bucket ID.

            Identifies the bucket used as the target for the translation.

            '
        database:
          type: string
          description: 'A database name.

            Identifies the InfluxDB v1 database.

            '
        retention_policy:
          type: string
          description: 'A [retention policy](https://docs.influxdata.com/influxdb/v1.8/concepts/glossary/#retention-policy-rp) name.

            Identifies the InfluxDB v1 retention policy mapping.

            '
        default:
          type: boolean
          description: 'If set to `true`, this DBRP mapping is the default retention policy

            for the database (specified by the `database` property''s value).

            '
        virtual:
          type: boolean
          description: Indicates an autogenerated, virtual mapping based on the bucket name. Currently only available in OSS.
        links:
          $ref: '#/components/schemas/Links'
      required:
      - id
      - orgID
      - bucketID
      - database
      - retention_policy
      - default
    DBRPs:
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/DBRP'
    DBRPUpdate:
      properties:
        retention_policy:
          type: string
          description: 'A [retention policy](https://docs.influxdata.com/influxdb/v1.8/concepts/glossary/#retention-policy-rp) name.

            Identifies the InfluxDB v1 retention policy mapping.

            '
        default:
          type: boolean
          description: 'Set to `true` to use this DBRP mapping as the default retention policy

            for the database (specified by the `database` property''s value).

            To remove the default mapping, set to `false`.

            '
    DBRPCreate:
      type: object
      properties:
        org:
          type: string
          description: 'An organization name.

            Identifies the [organization](https://docs.influxdata.com/influxdb/cloud/reference/glossary/#organization) that owns the mapping.

            '
        orgID:
          type: string
          description: 'An organization ID.

            Identifies the [organization](https://docs.influxdata.com/influxdb/cloud/reference/glossary/#organization) that owns the mapping.

            '
        bucketID:
          type: string
          description: 'A bucket ID.

            Identifies the bucket used as the target for the translation.

            '
        database:
          type: string
          description: 'A database name.

            Identifies the InfluxDB v1 database.

            '
        retention_policy:
          type: string
          description: 'A [retention policy](https://docs.influxdata.com/influxdb/v1.8/concepts/glossary/#retention-policy-rp) name.

            Identifies the InfluxDB v1 retention policy mapping.

            '
        default:
          type: boolean
          description: 'Set to `true` to use this DBRP mapping as the default retention policy

            for the database (specified by the `database` property''s value).

            '
      required:
      - bucketID
      - database
      - retention_policy
    DBRPGet:
      type: object
      properties:
        content:
          $ref: '#/components/schemas/DBRP'
          required: true
    Link:
      type: string
      format: uri
      readOnly: true
      description: URI of resource.
    Error:
      properties:
        code:
          description: code is the machine-readable error code.
          readOnly: true
          type: string
          enum:
          - internal error
          - not implemented
          - not found
          - conflict
          - invalid
          - unprocessable entity
          - empty value
          - unavailable
          - forbidden
          - too many requests
          - unauthorized
          - method not allowed
          - request too large
          - unsupported media type
        message:
          readOnly: true
          description: Human-readable message.
          type: string
        op:
          readOnly: true
          description: Describes the logical code operation when the error occurred. Useful for debugging.
          type: string
        err:
          readOnly: true
          description: Stack of errors that occurred during processing of the request. Useful for debugging.
          type: string
      required:
      - code
    Links:
      type: object
      description: 'URI pointers for additional paged results.

        '
      properties:
        next:
          $ref: '#/components/schemas/Link'
        self:
          $ref: '#/components/schemas/Link'
        prev:
          $ref: '#/components/schemas/Link'
      required:
      - self
  parameters:
    TraceSpan:
      in: header
      name: Zap-Trace-Span
      description: OpenTracing span context
      example:
        trace_id: '1'
        span_id: '1'
        baggage:
          key: value
      required: false
      schema:
        type: string
  securitySchemes:
    TokenAuthentication:
      type: apiKey
      name: Authorization
      in: header
      description: "Use the [Token authentication](#section/Authentication/TokenAuthentication)\nscheme to authenticate to the InfluxDB API.\n\nIn your API requests, send an `Authorization` header.\nFor the header value, provide the word `Token` followed by a space and an InfluxDB API token.\nThe word `Token` is case-sensitive.\n\n### Syntax\n\n`Authorization: Token INFLUX_API_TOKEN`\n\n### Example\n\n#### Use Token authentication with cURL\n\nThe following example shows how to use cURL to send an API request that uses Token authentication:\n\n```sh\ncurl --request GET \"INFLUX_URL/api/v2/buckets\" \\\n     --header \"Authorization: Token INFLUX_API_TOKEN\"\n```\n\nReplace the following:\n\n  - *`INFLUX_URL`*: your InfluxDB Cloud URL\n  - *`INFLUX_API_TOKEN`*: your [InfluxDB API token](https://docs.influxdata.com/influxdb/cloud/reference/glossary/#token)\n\n### Related endpoints\n\n- [`/authorizations` endpoints](#tag/Authorizations-(API-tokens))\n\n### Related guides\n\n- [Authorize API requests](https://docs.influxdata.com/influxdb/cloud/api-guide/api_intro/#authentication)\n- [Manage API tokens](https://docs.influxdata.com/influxdb/cloud/security/tokens/)\n"
    BasicAuthentication:
      type: http
      scheme: basic
      description: "### Basic authentication scheme\n\nUse the HTTP Basic authentication scheme for InfluxDB `/api/v2` API operations that support it:\n\n### Syntax\n\n`Authorization: Basic BASE64_ENCODED_CREDENTIALS`\n\nTo construct the `BASE64_ENCODED_CREDENTIALS`, combine the username and\nthe password with a colon (`USERNAME:PASSWORD`), and then encode the\nresulting string in [base64](https://developer.mozilla.org/en-US/docs/Glossary/Base64).\nMany HTTP clients encode the credentials for you before sending the\nrequest.\n\n_**Warning**: Base64-encoding can easily be reversed to obtain the original\nusername and password. It is used to keep the data intact and does not provide\nsecurity. You should always use HTTPS when authenticating or sending a request with\nsensitive information._\n\n### Examples\n\nIn the examples, replace the following:\n\n- **`EMAIL_ADDRESS`**: InfluxDB Cloud username (the email address the user signed up with)\n- **`PASSWORD`**: InfluxDB Cloud [API token](https://docs.influxdata.com/influxdb/cloud/reference/glossary/#token)\n- **`INFLUX_URL`**: your InfluxDB Cloud URL\n\n#### Encode credentials with cURL\n\nThe following example shows how to use cURL to send an API request that uses Basic authentication.\nWith the `--user` option, cURL encodes the credentials and passes them\nin the `Authorization: Basic` header.\n\n```sh\ncurl --get \"INFLUX_URL/api/v2/signin\"\n    --user \"EMAIL_ADDRESS\":\"PASSWORD\"\n```\n\n#### Encode credentials with Flux\n\nThe Flux [`http.basicAuth()` function](https://docs.influxdata.com/flux/v0.x/stdlib/http/basicauth/) returns a Base64-encoded\nbasic authentication header using a specified username and password combination.\n\n#### Encode credentials with JavaScript\n\nThe following example shows how to use the JavaScript `btoa()` function\nto create a Base64-encoded string:\n\n```js\nbtoa('EMAIL_ADDRESS:PASSWORD')\n```\n\nThe output is the following:\n\n```js\n'VVNFUk5BTUU6UEFTU1dPUkQ='\n```\n\nOnce you have the Base64-encoded credentials, you can pass them in the\n`Authorization` header--for example:\n\n```sh\ncurl --get \"INFLUX_URL/api/v2/signin\"\n    --header \"Authorization: Basic VVNFUk5BTUU6UEFTU1dPUkQ=\"\n```\n\nTo learn more about HTTP authentication, see\n[Mozilla Developer Network (MDN) Web Docs, HTTP authentication](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication)._\n"
x-tagGroups:
- name: Overview
  tags:
  - Quick start
  - Authentication
  - Supported operations
  - Headers
  - Pagination
  - Response codes
- name: Popular endpoints
  tags:
  - Data I/O endpoints
  - Security and access endpoints
  - System information endpoints
- name: All endpoints
  tags: []
