openapi: 3.2.0
info:
  title: Influxdata Users API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: '1.0'
  description: 'Operations tagged Users across 2 of this provider''s published API definitions: influxdata-cloud-openapi-original.yml, influxdata-oss-openapi-original.yml. Each path carries the servers of the definition it was published in.'
servers:
- url: /api/v2
security:
- TokenAuthentication: []
tags:
- name: Users
  description: Retrieve specific users.
paths:
  /me:
    get:
      operationId: GetMe
      tags:
      - Users
      summary: Retrieve the currently authenticated user
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      responses:
        '200':
          description: Success. The response body contains the currently authenticated user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '401':
          $ref: '#/components/responses/AuthorizationError'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/GeneralServerError'
    servers:
    - url: /api/v2
  /me/password:
    put:
      operationId: PutMePassword
      tags:
      - Users
      summary: Update a password
      description: 'Updates the password for the signed-in user.


        This endpoint represents the third step in the following three-step process to let a

        user with a user session update their password:

        1. Pass the user''s Basic authentication credentials to the `POST /api/v2/signin`

        endpoint to create a user session and generate a session cookie.

        2. From the response in the first step, extract the session cookie (`Set-Cookie`) header.

        3. Pass the following in a request to the `PUT /api/v2/me/password` endpoint:

        - The `Set-Cookie` header from the second step

        - The `Authorization Basic` header with the user''s _Basic authentication_ credentials

        - `{"password": "NEW_PASSWORD"}` in the request body


        #### InfluxDB Cloud


        - Doesn''t let you manage user passwords through the API.

        Use the InfluxDB Cloud user interface (UI) to update your password.


        #### Related endpoints


        - Signin

        - Signout

        - Users


        #### Related guides


        - InfluxDB Cloud - Change your password

        - InfluxDB OSS - Change your password'
      security:
      - BasicAuthentication: []
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - name: influxdb-oss-session
        in: cookie
        schema:
          type: string
        required: true
        description: 'The user session cookie for the

          [user](https://docs.influxdata.com/influxdb/cloud/reference/glossary/#user)

          signed in with [Basic authentication credentials](#section/Authentication/BasicAuthentication).


          #### Related guides


          - [Manage users]({{% INFLUXDB_DOCS_URL%}}/users/)

          '
        example: influxdb-oss-session=19aaaZZZGOvP2GGryXVT2qYftlFKu3bIopurM6AGFow1yF1abhtOlbHfsc-d8gozZFC_6WxmlQIAwLMW5xs523w==
      requestBody:
        description: The new password.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordResetBody'
      responses:
        '204':
          description: Success. The password is updated.
        '400':
          description: 'Bad request.


            #### InfluxDB Cloud


            - Doesn''t let you manage user passwords through the API; always responds with this status.


            #### InfluxDB OSS


            - Doesn''t understand a value passed in the request.

            '
        '401':
          $ref: '#/components/responses/AuthorizationError'
        default:
          description: Unsuccessful authentication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    servers:
    - url: /api/v2
  /users/{userID}/password:
    post:
      operationId: PostUsersIDPassword
      tags:
      - Users
      summary: Update a password
      description: 'Updates a user password.


        #### InfluxDB Cloud


        - Doesn''t allow you to manage user passwords through the API.

        Use the InfluxDB Cloud user interface (UI) to update a password.


        #### Related guides


        - InfluxDB Cloud - Change your password

        - InfluxDB OSS - Change your password'
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - in: path
        name: userID
        schema:
          type: string
        required: true
        description: The ID of the user to set the password for.
      requestBody:
        description: The new password to set for the user.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordResetBody'
      responses:
        '204':
          description: Success. The password is updated.
        '400':
          description: 'Bad request.


            #### InfluxDB Cloud


            - Doesn''t allow you to manage passwords through the API; always responds with this status.


            #### InfluxDB OSS


            - Doesn''t understand a value passed in the request.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                updatePasswordNotAllowed:
                  summary: Cloud API can't update passwords
                  value:
                    code: invalid
                    message: passwords cannot be changed through the InfluxDB Cloud API
        default:
          description: Unexpected error
          $ref: '#/components/responses/GeneralServerError'
      x-codeSamples:
      - lang: Shell
        label: 'cURL: use HTTP POST to update the user password'
        source: "curl --request POST \\\n   \"http://localhost:8086/api/v2/users/USER_ID/password\" \\\n  --header 'Content-type: application/json' \\\n  --header \"Authorization: Token INFLUX_TOKEN\" \\\n  --data-binary @- << EOF\n    {\"password\": \"NEW_USER_PASSWORD\"}\nEOF\n"
    put:
      operationId: PutUsersIDPassword
      tags:
      - Users
      summary: Update a password
      description: 'Updates a user password.


        Use this endpoint to let a user authenticate with

        Basic authentication credentials

        and set a new password.


        #### InfluxDB Cloud


        - Doesn''t allow you to manage user passwords through the API.

        Use the InfluxDB Cloud user interface (UI) to update a password.


        #### Related guides


        - InfluxDB Cloud - Change your password

        - InfluxDB OSS - Change your password'
      security:
      - BasicAuthentication: []
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - in: path
        name: userID
        schema:
          type: string
        required: true
        description: The ID of the user to set the password for.
      requestBody:
        description: The new password to set for the user.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordResetBody'
      responses:
        '204':
          description: Success. The password is updated.
        '400':
          description: 'Bad request.


            #### InfluxDB Cloud


            - Doesn''t allow you to manage passwords through the API; always responds with this status.


            #### InfluxDB OSS


            - Doesn''t understand a value passed in the request.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                updatePasswordNotAllowed:
                  summary: Cloud API can't update passwords
                  value:
                    code: invalid
                    message: passwords cannot be changed through the InfluxDB Cloud API
        default:
          description: Unexpected error
          $ref: '#/components/responses/GeneralServerError'
      x-codeSamples:
      - lang: Shell
        label: 'cURL: use Basic auth to update the user password'
        source: "curl -c ./cookie-file.tmp --request POST \\\n   \"http://localhost:8086/api/v2/signin\" \\\n  --user \"${INFLUX_USER_NAME}:${INFLUX_USER_PASSWORD}\"\n\ncurl -b ./cookie-file.tmp --request PUT \\\n   \"http://localhost:8086/api/v2/users/USER_ID/password\" \\\n  --header 'Content-type: application/json' \\\n  --data-binary @- << EOF\n    {\"password\": \"NEW_USER_PASSWORD\"}\nEOF\n"
    servers:
    - url: /api/v2
  /users:
    get:
      operationId: GetUsers
      tags:
      - Users
      summary: List users
      description: 'Lists users.


        To limit which users are returned, pass query parameters in your request.


        #### InfluxDB Cloud


        - InfluxDB Cloud doesn''t allow listing all users through the API.

        Use the InfluxDB Cloud user interface (UI) to manage account information.


        #### Required permissions for InfluxDB Cloud


        | Action | Permission required | Restriction |

        |:-------|:--------------------|:------------|

        | List all users | Operator token | InfluxData internal use only |

        | List a specific user | `read-users` or `read-user USER_ID` |


        *`USER_ID`* is the ID of the user that you want to retrieve.


        #### Related guides


        - Manage users'
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - in: query
        name: name
        schema:
          type: string
        description: 'A user name.

          Only lists the specified [user](https://docs.influxdata.com/influxdb/cloud/reference/glossary/#user).

          '
      - in: query
        name: id
        schema:
          type: string
        description: 'A user id.

          Only lists the specified [user](https://docs.influxdata.com/influxdb/cloud/reference/glossary/#user).

          '
      responses:
        '200':
          description: "Success. The response contains a list of `users`.\n\n#### InfluxDB Cloud\n\n- Returns an empty `users` list if you don't pass _`id`_ or _`name`_ parameters and don't use an\n  _operator token_.\n  Only InfluxData can access InfluxDB Cloud operator tokens.\n"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
        '401':
          description: 'Unauthorized.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: "Unprocessable entity.\n\nThe error may indicate one of the following problems:\n\n- The request body isn't valid--the request is well-formed,\n  but InfluxDB can't process it due to semantic errors.\n- You passed a parameter combination that InfluxDB doesn't support.\n"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          description: Unexpected error
          $ref: '#/components/responses/GeneralServerError'
    post:
      operationId: PostUsers
      tags:
      - Users
      summary: Create a user
      description: '(InfluxData internal use only)


        Creates and returns a user

        that can access InfluxDB.


        #### InfluxDB Cloud


        - InfluxDB Cloud Doesn''t let you manage users through the API.

        Use the InfluxDB Cloud user interface (UI) to manage account information.


        #### Required permissions for InfluxDB Cloud


        | Action | Permission required | Restriction |

        |:-------|:--------------------|:------------|

        | Create user | Operator token | InfluxData internal use only |


        #### Related guides


        - Manage users'
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      requestBody:
        description: In the request body, provide the user.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: 'Success.

            The response body contains the user.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '401':
          description: "Unauthorized.\n\n#### InfluxDB Cloud\n\n- Returns this error if the request doesn't use an _operator token_.\n  Only InfluxData can access InfluxDB Cloud operator tokens.\n"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: "Unprocessable entity.\n\nThe error may indicate one of the following problems:\n\n- The request body isn't valid--the request is well-formed,\n  but InfluxDB can't process it due to semantic errors.\n- You passed a parameter combination that InfluxDB doesn't support.\n"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          description: Unexpected error
          $ref: '#/components/responses/GeneralServerError'
    servers:
    - url: /api/v2
  /users/{userID}:
    get:
      operationId: GetUsersID
      tags:
      - Users
      summary: Retrieve a user
      description: 'Retrieves a user.


        #### Related guides


        - Manage users'
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - in: path
        name: userID
        schema:
          type: string
        required: true
        description: 'A user ID.

          Retrieves the specified [user](https://docs.influxdata.com/influxdb/cloud/reference/glossary/#user).

          '
      responses:
        '200':
          description: Success. The response body contains the user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        default:
          description: Unexpected error
          $ref: '#/components/responses/GeneralServerError'
    patch:
      operationId: PatchUsersID
      tags:
      - Users
      summary: Update a user
      description: '(InfluxData internal use only)


        Updates a user and returns the user.


        #### InfluxDB Cloud


        - Doesn''t let you manage users through the API.

        Use the InfluxDB Cloud user interface (UI) to manage account information.


        #### Required permissions for InfluxDB Cloud


        | Action | Permission required | Restriction |

        |:-------|:--------------------|:------------|

        | Update user | Operator token | InfluxData internal use only |


        #### Related guides


        - Manage users'
      requestBody:
        description: The user update to apply.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - in: path
        name: userID
        schema:
          type: string
        required: true
        description: 'A user ID.

          Updates the specified [user](https://docs.influxdata.com/influxdb/cloud/reference/glossary/#user).

          '
      responses:
        '200':
          description: Success. The response body contains the updated user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/AuthorizationError'
        '404':
          $ref: '#/components/responses/ResourceNotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/GeneralServerError'
    delete:
      operationId: DeleteUsersID
      tags:
      - Users
      summary: Delete a user
      description: '(InfluxData internal use only)


        Deletes a user.


        For security purposes, once an InfluxDB user account is deleted from an

        organization, the user (and their token) cannot be reactivated.


        #### InfluxDB Cloud


        - Doesn''t let you manage users through the API.

        Use the InfluxDB Cloud user interface (UI) to manage account information.


        #### Required permissions


        | Action | Permission required | Restriction |

        |:-------|:--------------------|:------------|

        | Delete user | Operator token | InfluxData internal use only |


        #### Related guides


        - Manage users'
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - in: path
        name: userID
        schema:
          type: string
        required: true
        description: 'A user ID.

          Deletes the specified [user](https://docs.influxdata.com/influxdb/cloud/reference/glossary/#user).

          '
      responses:
        '204':
          description: Success. The user is deleted.
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/AuthorizationError'
        '404':
          $ref: '#/components/responses/ResourceNotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/GeneralServerError'
    servers:
    - url: /api/v2
components:
  responses:
    ResourceNotFoundError:
      description: "Not found.\nA requested resource was not found.\nThe response body contains the requested resource type and the name value\n(if you passed it)--for example:\n\n- `\"organization name \\\"my-org\\\" not found\"`\n- `\"organization not found\"`: indicates you passed an ID that did not match\n   an organization.\n"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            org-not-found:
              summary: Organization name not found
              value:
                code: not found
                message: organization name "my-org" not found
            bucket-not-found:
              summary: Bucket name not found
              value:
                code: not found
                message: bucket "air_sensor" not found
            orgID-not-found:
              summary: Organization ID not found
              value:
                code: not found
                message: organization not found
    BadRequestError:
      description: 'Bad request.

        The response body contains detail about the error.


        #### InfluxDB OSS


        - Returns this error if an incorrect value is passed in the `org` parameter or `orgID` parameter.

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            orgProvidedNotFound:
              summary: The org or orgID passed doesn't own the token passed in the header
              value:
                code: invalid
                message: 'failed to decode request body: organization not found'
    GeneralServerError:
      description: Non 2XX error response from server.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    AuthorizationError:
      description: "Unauthorized. The error may indicate one of the following:\n\n  * The `Authorization: Token` header is missing or malformed.\n  * The API token value is missing from the header.\n  * The token doesn't have sufficient permissions to write to this organization and bucket.\n"
      content:
        application/json:
          schema:
            properties:
              code:
                description: 'The HTTP status code description. Default is `unauthorized`.

                  '
                readOnly: true
                type: string
                enum:
                - unauthorized
              message:
                readOnly: true
                description: A human-readable message that may contain detail about the error.
                type: string
          examples:
            tokenNotAuthorized:
              summary: Token is not authorized to access a resource
              value:
                code: unauthorized
                message: unauthorized access
    InternalServerError:
      description: 'Internal server error.

        The server encountered an unexpected situation.

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    User:
      properties:
        id:
          readOnly: true
          type: string
        name:
          type: string
        status:
          description: If inactive the user is inactive.
          default: active
          type: string
          enum:
          - active
          - inactive
        role:
          type: string
          enum:
          - owner
          - member
        org_id:
          type: string
      required:
      - name
    UserResponse:
      properties:
        id:
          readOnly: true
          type: string
          description: 'The user ID.

            '
        name:
          type: string
          description: 'The user name.

            '
        status:
          description: 'The status of a user.

            An inactive user can''t read or write resources.

            '
          default: active
          type: string
          enum:
          - active
          - inactive
        links:
          type: object
          readOnly: true
          example:
            self: /api/v2/users/1
          properties:
            self:
              type: string
              format: uri
      required:
      - name
    Error:
      properties:
        code:
          description: code is the machine-readable error code.
          readOnly: true
          type: string
          enum:
          - internal error
          - not implemented
          - not found
          - conflict
          - invalid
          - unprocessable entity
          - empty value
          - unavailable
          - forbidden
          - too many requests
          - unauthorized
          - method not allowed
          - request too large
          - unsupported media type
        message:
          readOnly: true
          description: Human-readable message.
          type: string
        op:
          readOnly: true
          description: Describes the logical code operation when the error occurred. Useful for debugging.
          type: string
        err:
          readOnly: true
          description: Stack of errors that occurred during processing of the request. Useful for debugging.
          type: string
      required:
      - code
    PasswordResetBody:
      properties:
        password:
          type: string
      required:
      - password
    Users:
      type: object
      properties:
        links:
          type: object
          properties:
            self:
              type: string
              format: uri
        users:
          type: array
          items:
            $ref: '#/components/schemas/UserResponse'
    User_2:
      properties:
        id:
          readOnly: true
          type: string
          description: The user ID.
        name:
          type: string
          description: The user name.
        status:
          description: 'If `inactive`, the user is inactive.

            Default is `active`.

            '
          default: active
          type: string
          enum:
          - active
          - inactive
      required:
      - name
  parameters:
    TraceSpan:
      in: header
      name: Zap-Trace-Span
      description: OpenTracing span context
      example:
        trace_id: '1'
        span_id: '1'
        baggage:
          key: value
      required: false
      schema:
        type: string
    After:
      in: query
      name: after
      required: false
      schema:
        type: string
      description: 'A resource ID to seek from.

        Returns records created after the specified record;

        results don''t include the specified record.


        Use `after` instead of the `offset` parameter.

        For more information about pagination parameters, see [Pagination](https://docs.influxdata.com/influxdb/latest/api/#tag/Pagination).

        '
    Offset:
      in: query
      name: offset
      required: false
      description: 'The offset for pagination.

        The number of records to skip.


        For more information about pagination parameters, see [Pagination](https://docs.influxdata.com/influxdb/latest/api/#tag/Pagination).

        '
      schema:
        type: integer
        minimum: 0
    Limit:
      in: query
      name: limit
      required: false
      description: 'Limits the number of records returned. Default is `20`.

        '
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20
  securitySchemes:
    TokenAuthentication:
      type: apiKey
      name: Authorization
      in: header
      description: "Use the [Token authentication](#section/Authentication/TokenAuthentication)\nscheme to authenticate to the InfluxDB API.\n\nIn your API requests, send an `Authorization` header.\nFor the header value, provide the word `Token` followed by a space and an InfluxDB API token.\nThe word `Token` is case-sensitive.\n\n### Syntax\n\n`Authorization: Token INFLUX_API_TOKEN`\n\n### Example\n\n#### Use Token authentication with cURL\n\nThe following example shows how to use cURL to send an API request that uses Token authentication:\n\n```sh\ncurl --request GET \"INFLUX_URL/api/v2/buckets\" \\\n     --header \"Authorization: Token INFLUX_API_TOKEN\"\n```\n\nReplace the following:\n\n  - *`INFLUX_URL`*: your InfluxDB Cloud URL\n  - *`INFLUX_API_TOKEN`*: your [InfluxDB API token](https://docs.influxdata.com/influxdb/cloud/reference/glossary/#token)\n\n### Related endpoints\n\n- [`/authorizations` endpoints](#tag/Authorizations-(API-tokens))\n\n### Related guides\n\n- [Authorize API requests](https://docs.influxdata.com/influxdb/cloud/api-guide/api_intro/#authentication)\n- [Manage API tokens](https://docs.influxdata.com/influxdb/cloud/security/tokens/)\n"
    BasicAuthentication:
      type: http
      scheme: basic
      description: "### Basic authentication scheme\n\nUse the HTTP Basic authentication scheme for InfluxDB `/api/v2` API operations that support it:\n\n### Syntax\n\n`Authorization: Basic BASE64_ENCODED_CREDENTIALS`\n\nTo construct the `BASE64_ENCODED_CREDENTIALS`, combine the username and\nthe password with a colon (`USERNAME:PASSWORD`), and then encode the\nresulting string in [base64](https://developer.mozilla.org/en-US/docs/Glossary/Base64).\nMany HTTP clients encode the credentials for you before sending the\nrequest.\n\n_**Warning**: Base64-encoding can easily be reversed to obtain the original\nusername and password. It is used to keep the data intact and does not provide\nsecurity. You should always use HTTPS when authenticating or sending a request with\nsensitive information._\n\n### Examples\n\nIn the examples, replace the following:\n\n- **`EMAIL_ADDRESS`**: InfluxDB Cloud username (the email address the user signed up with)\n- **`PASSWORD`**: InfluxDB Cloud [API token](https://docs.influxdata.com/influxdb/cloud/reference/glossary/#token)\n- **`INFLUX_URL`**: your InfluxDB Cloud URL\n\n#### Encode credentials with cURL\n\nThe following example shows how to use cURL to send an API request that uses Basic authentication.\nWith the `--user` option, cURL encodes the credentials and passes them\nin the `Authorization: Basic` header.\n\n```sh\ncurl --get \"INFLUX_URL/api/v2/signin\"\n    --user \"EMAIL_ADDRESS\":\"PASSWORD\"\n```\n\n#### Encode credentials with Flux\n\nThe Flux [`http.basicAuth()` function](https://docs.influxdata.com/flux/v0.x/stdlib/http/basicauth/) returns a Base64-encoded\nbasic authentication header using a specified username and password combination.\n\n#### Encode credentials with JavaScript\n\nThe following example shows how to use the JavaScript `btoa()` function\nto create a Base64-encoded string:\n\n```js\nbtoa('EMAIL_ADDRESS:PASSWORD')\n```\n\nThe output is the following:\n\n```js\n'VVNFUk5BTUU6UEFTU1dPUkQ='\n```\n\nOnce you have the Base64-encoded credentials, you can pass them in the\n`Authorization` header--for example:\n\n```sh\ncurl --get \"INFLUX_URL/api/v2/signin\"\n    --header \"Authorization: Basic VVNFUk5BTUU6UEFTU1dPUkQ=\"\n```\n\nTo learn more about HTTP authentication, see\n[Mozilla Developer Network (MDN) Web Docs, HTTP authentication](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication)._\n"
x-refined-from:
- influxdata-cloud-openapi-original.yml
- influxdata-oss-openapi-original.yml
x-tagGroups:
- name: Overview
  tags:
  - Quick start
  - Authentication
  - Supported operations
  - Headers
  - Pagination
  - Response codes
- name: Popular endpoints
  tags:
  - Data I/O endpoints
  - Security and access endpoints
  - System information endpoints
- name: All endpoints
  tags: []
