openapi: 3.0.0
info:
  title: InfluxDB Cloud API Service Authorizations (API tokens) Authorizations (API tokens) Organizations API
  version: 2.0.1
  description: 'The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.

    '
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
- url: /api/v2
security:
- TokenAuthentication: []
tags:
- name: Organizations
  description: 'Manage your [organization](https://docs.influxdata.com/influxdb/cloud/reference/glossary/#organization).

    An organization is a workspace for a group of users. Organizations can be

    used to separate different environments, projects, teams or users within

    InfluxDB.


    Use the `/api/v2/orgs` endpoints to view and manage organizations.

    '
paths:
  /orgs:
    get:
      operationId: GetOrgs
      tags:
      - Organizations
      summary: List organizations
      description: 'Lists [organizations](https://docs.influxdata.com/influxdb/cloud/reference/glossary/#organization/).


        To limit which organizations are returned, pass query parameters in your request.

        If no query parameters are passed, InfluxDB returns all organizations up to the default `limit`.


        #### InfluxDB Cloud


        - Only returns the organization that owns the token passed in the request.


        #### Related guides


        - [View organizations](https://docs.influxdata.com/influxdb/cloud/organizations/view-orgs/)

        '
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - $ref: '#/components/parameters/Offset'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Descending'
      - in: query
        name: org
        schema:
          type: string
        description: 'An organization name.

          Only returns the specified organization.

          '
      - in: query
        name: orgID
        schema:
          type: string
        description: 'An organization ID.

          Only returns the specified organization.

          '
      - in: query
        name: userID
        schema:
          type: string
        description: 'A user ID.

          Only returns organizations where the specified user is a member or owner.

          '
      responses:
        '200':
          description: Success. The response body contains a list of organizations.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organizations'
              examples:
                successResponse:
                  value:
                    links:
                      self: /api/v2/orgs
                    orgs:
                    - links:
                        buckets: /api/v2/buckets?org=INFLUX_ORG
                        dashboards: /api/v2/dashboards?org=INFLUX_ORG
                        labels: /api/v2/orgs/INFLUX_ORG_ID/labels
                        logs: /api/v2/orgs/INFLUX_ORG_ID/logs
                        members: /api/v2/orgs/INFLUX_ORG_ID/members
                        owners: /api/v2/orgs/INFLUX_ORG_ID/owners
                        secrets: /api/v2/orgs/INFLUX_ORG_ID/secrets
                        self: /api/v2/orgs/INFLUX_ORG_ID
                        tasks: /api/v2/tasks?org=InfluxData
                      id: INFLUX_ORG_ID
                      name: INFLUX_ORG
                      description: Example InfluxDB organization
                      createdAt: '2022-07-17T23:00:30.778487Z'
                      updatedAt: '2022-07-17T23:00:30.778487Z'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/AuthorizationError'
        '404':
          $ref: '#/components/responses/ResourceNotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/GeneralServerError'
    post:
      operationId: PostOrgs
      tags:
      - Organizations
      summary: Create an organization
      description: 'Creates an [organization](https://docs.influxdata.com/influxdb/cloud/reference/glossary/#organization)

        and returns the newly created organization.


        #### InfluxDB Cloud


        - Doesn''t allow you to use this endpoint to create organizations.


        #### Related guides


        - [Manage organizations](https://docs.influxdata.com/influxdb/cloud/organizations)

        '
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      requestBody:
        description: The organization to create.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostOrganizationRequest'
      responses:
        '201':
          description: Created. The response body contains the organization information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
              examples:
                successResponse:
                  value:
                    links:
                      buckets: /api/v2/buckets?org=INFLUX_ORG
                      dashboards: /api/v2/dashboards?org=INFLUX_ORG
                      labels: /api/v2/orgs/INFLUX_ORG_ID/labels
                      logs: /api/v2/orgs/INFLUX_ORG_ID/logs
                      members: /api/v2/orgs/INFLUX_ORG_ID/members
                      owners: /api/v2/orgs/INFLUX_ORG_ID/owners
                      secrets: /api/v2/orgs/INFLUX_ORG_ID/secrets
                      self: /api/v2/orgs/INFLUX_ORG_ID
                      tasks: /api/v2/tasks?org=INFLUX_ORG
                    id: INFLUX_ORG_ID
                    name: INFLUX_ORG
                    description: ''
                    createdAt: '2022-08-24T23:05:52.881317Z'
                    updatedAt: '2022-08-24T23:05:52.881318Z'
        '400':
          $ref: '#/components/responses/BadRequestError'
          examples:
            invalidRequest:
              summary: The `name` field is missing from the request body.
              value:
                code: invalid
                message: org name is empty
        '401':
          $ref: '#/components/responses/AuthorizationError'
        '404':
          $ref: '#/components/responses/ResourceNotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-codeSamples:
      - lang: Shell
        label: cURL
        source: "curl --request POST \"http://localhost:8086/api/v2/orgs \\\n  --header \"Authorization: Token INFLUX_API_TOKEN\" \\\n  --header \"Accept: application/json\" \\\n  --header \"Content-Type: application/json\" \\\n  --data '{\n      \"name\": \"INFLUX_ORG\",\n      \"description: \"Example InfluxDB organization\"\n    }'\n"
  /orgs/{orgID}:
    get:
      operationId: GetOrgsID
      tags:
      - Organizations
      summary: Retrieve an organization
      description: 'Retrieves an organization.


        Use this endpoint to retrieve information for a specific organization.


        #### Related guides


        - [View organizations](https://docs.influxdata.com/influxdb/cloud/organizations/view-orgs/)

        '
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - in: path
        name: orgID
        schema:
          type: string
        required: true
        description: 'The ID of the organization to retrieve.

          '
      responses:
        '200':
          description: 'Success.

            The response body contains the organization information.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
        '401':
          $ref: '#/components/responses/AuthorizationError'
        '404':
          description: 'Not found.

            Organization not found.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                notFound:
                  summary: 'The requested organization wasn''t found.

                    '
                  value:
                    code: not found
                    message: organization not found
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      operationId: PatchOrgsID
      tags:
      - Organizations
      summary: Update an organization
      description: 'Updates an organization.


        Use this endpoint to update properties

        (`name`, `description`) of an organization.


        Updating an organization’s name affects all resources that reference the

        organization by name, including the following:


        - Queries

        - Dashboards

        - Tasks

        - Telegraf configurations

        - Templates


        If you change an organization name, be sure to update the organization name

        in these resources as well.


        #### Related Guides


        - [Update an organization](https://docs.influxdata.com/influxdb/cloud/organizations/update-org/)

        '
      requestBody:
        description: The organization update to apply.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchOrganizationRequest'
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - in: path
        name: orgID
        schema:
          type: string
        required: true
        description: 'The ID of the organization to update.

          '
      responses:
        '200':
          description: Success. The response body contains the updated organization.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/AuthorizationError'
        '404':
          $ref: '#/components/responses/ResourceNotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      operationId: DeleteOrgsID
      tags:
      - Organizations
      summary: Delete an organization
      description: "Deletes an organization.\n\nDeleting an organization from InfluxDB Cloud can't be undone.\nOnce deleted, all data associated with the organization is removed.\n\n#### InfluxDB Cloud\n\n- Does the following when you send a delete request:\n\n  1. Validates the request and queues the delete.\n  2. Returns an HTTP `204` status code if queued; _error_ otherwise.\n  3. Handles the delete asynchronously.\n\n#### InfluxDB OSS\n\n- Validates the request, handles the delete synchronously,\nand then responds with success or failure.\n\n#### Limitations\n\n- Only one organization can be deleted per request.\n\n#### Related guides\n\n- [Delete organizations](https://docs.influxdata.com/influxdb/cloud/organizations/delete-orgs/)\n"
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - in: path
        name: orgID
        schema:
          type: string
        required: true
        description: 'The ID of the organization to delete.

          '
      responses:
        '204':
          description: "Success.\n\n#### InfluxDB Cloud\n  - The organization is queued for deletion.\n\n#### InfluxDB OSS\n  - The organization is deleted.\n"
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/AuthorizationError'
        '404':
          description: 'Not found.

            InfluxDB can''t find the organization.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                notFound:
                  summary: 'The requested organization was not found.

                    '
                  value:
                    code: not found
                    message: org not found
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /orgs/{orgID}/members:
    get:
      operationId: GetOrgsIDMembers
      tags:
      - Organizations
      summary: List all members of an organization
      description: "Lists all users that belong to an organization.\n\nInfluxDB [users](https://docs.influxdata.com/influxdb/cloud/reference/glossary/#user) have\npermission to access InfluxDB.\n\n[Members](https://docs.influxdata.com/influxdb/cloud/reference/glossary/#member) are users\nwithin the organization.\n\n#### InfluxDB Cloud\n\n- Doesn't use `owner` and `member` roles.\n  Use [`/api/v2/authorizations`](#tag/Authorizations-(API-tokens)) to assign user permissions.\n\n#### Limitations\n\n- Member permissions are separate from API token permissions.\n- Member permissions are used in the context of the InfluxDB UI.\n\n#### Required permissions\n\n- `read-orgs INFLUX_ORG_ID`\n\n*`INFLUX_ORG_ID`* is the ID of the organization that you want to retrieve\nmembers for.\n\n#### Related guides\n\n- [Manage users](https://docs.influxdata.com/influxdb/cloud/users/)\n- [Manage members](https://docs.influxdata.com/influxdb/cloud/organizations/members/)\n"
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - in: path
        name: orgID
        schema:
          type: string
        required: true
        description: 'The ID of the organization to retrieve users for.

          '
      responses:
        '200':
          description: 'Success.

            The response body contains a list of all users within the organization.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceMembers'
              examples:
                successResponse:
                  value:
                    links:
                      self: /api/v2/orgs/055aa4783aa38398/members
                    users:
                    - role: member
                      links:
                        self: /api/v2/users/791df274afd48a83
                      id: 791df274afd48a83
                      name: example_user_1
                      status: active
                    - role: owner
                      links:
                        self: /api/v2/users/09cfb87051cbe000
                      id: 09cfb87051cbe000
                      name: example_user_2
                      status: active
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/AuthorizationError'
        '404':
          description: 'Not found.

            InfluxDB can''t find the organization.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                notFound:
                  summary: 'The requested organization wasn''t found.

                    '
                  value:
                    code: not found
                    message: 404 page not found
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      operationId: PostOrgsIDMembers
      tags:
      - Organizations
      summary: Add a member to an organization
      description: "Add a user to an organization.\n\nInfluxDB [users](https://docs.influxdata.com/influxdb/cloud/reference/glossary/#user) have\npermission to access InfluxDB.\n\n[Members](https://docs.influxdata.com/influxdb/cloud/reference/glossary/#member) are users\nwithin the organization.\n\n#### InfluxDB Cloud\n- Doesn't use `owner` and `member` roles.\n  Use [`/api/v2/authorizations`](#tag/Authorizations-(API-tokens)) to assign user permissions.\n\n#### Limitations\n\n- Member permissions are separate from API token permissions.\n- Member permissions are used in the context of the InfluxDB UI.\n\n#### Required permissions\n\n- `write-orgs INFLUX_ORG_ID`\n\n*`INFLUX_ORG_ID`* is the ID of the organization that you want to add a member to.\n\n#### Related guides\n\n- [Manage users](https://docs.influxdata.com/influxdb/cloud/users/)\n- [Manage members](https://docs.influxdata.com/influxdb/cloud/organizations/members/)\n"
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - in: path
        name: orgID
        schema:
          type: string
        required: true
        description: 'The ID of the organization.

          '
      requestBody:
        description: 'The user to add to the organization.

          '
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddResourceMemberRequestBody'
      responses:
        '201':
          description: 'Success.

            The response body contains the user information.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceMember'
              examples:
                successResponse:
                  value:
                    role: member
                    links:
                      self: /api/v2/users/09cfb87051cbe000
                    id: 09cfb87051cbe000
                    name: example_user_1
                    status: active
        '400':
          $ref: '#/components/responses/BadRequestError'
          examples:
            invalidRequest:
              summary: The user `id` is missing from the request body.
              value:
                code: invalid
                message: user id missing or invalid
        '401':
          $ref: '#/components/responses/AuthorizationError'
        '404':
          $ref: '#/components/responses/ResourceNotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-codeSamples:
      - lang: Shell
        label: cURL
        source: "curl --request POST \"http://localhost:8086/api/v2/orgs/INFLUX_ORG_ID/members \\\n  --header \"Authorization: Token INFLUX_API_TOKEN\" \\\n  --header \"Accept: application/json\" \\\n  --header \"Content-Type: application/json\" \\\n  --data '{\n      \"id\": \"09cfb87051cbe000\"\n    }'\n"
  /orgs/{orgID}/members/{userID}:
    delete:
      operationId: DeleteOrgsIDMembersID
      tags:
      - Organizations
      summary: Remove a member from an organization
      description: "Removes a member from an organization.\n\nUse this endpoint to remove a user's member privileges for an organization.\nRemoving member privileges removes the user's `read` and `write` permissions\nfrom the organization.\n\n#### InfluxDB Cloud\n\n- Doesn't use `owner` and `member` roles.\n  Use [`/api/v2/authorizations`](#tag/Authorizations-(API-tokens)) to assign user permissions.\n\n#### Limitations\n\n- Member permissions are separate from API token permissions.\n- Member permissions are used in the context of the InfluxDB UI.\n\n#### Required permissions\n\n- `write-orgs INFLUX_ORG_ID`\n\n*`INFLUX_ORG_ID`* is the ID of the organization that you want to remove an\nowner from.\n\n#### Related guides\n\n- [Manage members](https://docs.influxdata.com/influxdb/cloud/organizations/members/)\n"
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - in: path
        name: userID
        schema:
          type: string
        required: true
        description: The ID of the user to remove.
      - in: path
        name: orgID
        schema:
          type: string
        required: true
        description: The ID of the organization to remove a user from.
      responses:
        '204':
          description: 'Success.

            The user is no longer a member of the organization.

            '
        '401':
          $ref: '#/components/responses/AuthorizationError'
        '404':
          $ref: '#/components/responses/ResourceNotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /orgs/{orgID}/owners:
    get:
      operationId: GetOrgsIDOwners
      tags:
      - Organizations
      summary: List all owners of an organization
      description: "Lists all owners of an organization.\n\n#### InfluxDB Cloud\n\n- Doesn't use `owner` and `member` roles.\n  Use [`/api/v2/authorizations`](#tag/Authorizations-(API-tokens)) to assign user permissions.\n\n#### Required permissions\n\n- `read-orgs INFLUX_ORG_ID`\n\n*`INFLUX_ORG_ID`* is the ID of the organization that you want to retrieve a\nlist of owners from.\n"
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - in: path
        name: orgID
        schema:
          type: string
        required: true
        description: 'The ID of the organization to list owners for.

          '
      responses:
        '200':
          description: A list of organization owners
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceOwners'
              examples:
                successResponse:
                  value:
                    links:
                      self: /api/v2/orgs/055aa4783aa38398/owners
                    users:
                    - role: owner
                      links:
                        self: /api/v2/users/09cfb87051cbe000
                      id: 09cfb87051cbe000
                      name: example_user_2
                      status: active
        '404':
          description: Organization not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      operationId: PostOrgsIDOwners
      tags:
      - Organizations
      summary: Add an owner to an organization
      description: "Adds an owner to an organization.\n\nUse this endpoint to assign the organization `owner` role to a user.\n\n#### InfluxDB Cloud\n\n- Doesn't use `owner` and `member` roles.\n  Use [`/api/v2/authorizations`](#tag/Authorizations-(API-tokens)) to assign user permissions.\n\n#### Required permissions\n\n- `write-orgs INFLUX_ORG_ID`\n\n*`INFLUX_ORG_ID`* is the ID of the organization that you want to add an owner for.\n\n#### Related endpoints\n\n- [Authorizations](#tag/Authorizations-(API-tokens))\n"
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - in: path
        name: orgID
        schema:
          type: string
        required: true
        description: The ID of the organization that you want to add an owner for.
      requestBody:
        description: The user to add as an owner of the organization.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddResourceMemberRequestBody'
            examples:
              successResponse:
                value:
                  role: owner
                  links:
                    self: /api/v2/users/09cfb87051cbe000
                  id: 09cfb87051cbe000
                  name: example_user_1
                  status: active
      responses:
        '201':
          description: 'Success. The user is an owner of the organization.

            The response body contains the owner with role and user detail.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceOwner'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/AuthorizationError'
        '404':
          $ref: '#/components/responses/ResourceNotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-codeSamples:
      - lang: Shell
        label: cURL
        source: "curl --request POST \"http://localhost:8086/api/v2/orgs/INFLUX_ORG_ID/owners \\\n  --header \"Authorization: Token INFLUX_API_TOKEN\" \\\n  --header \"Accept: application/json\" \\\n  --header \"Content-Type: application/json\" \\\n  --data '{\n      \"id\": \"09cfb87051cbe000\"\n    }'\n"
  /orgs/{orgID}/owners/{userID}:
    delete:
      operationId: DeleteOrgsIDOwnersID
      tags:
      - Organizations
      summary: Remove an owner from an organization
      description: "Removes an [owner](https://docs.influxdata.com/influxdb/cloud/reference/glossary/#owner) from\nthe organization.\n\nOrganization owners have permission to delete organizations and remove user and member\npermissions from the organization.\n\n#### InfluxDB Cloud\n- Doesn't use `owner` and `member` roles.\n  Use [`/api/v2/authorizations`](#tag/Authorizations-(API-tokens)) to assign user permissions.\n\n#### Limitations\n\n- Owner permissions are separate from API token permissions.\n- Owner permissions are used in the context of the InfluxDB UI.\n\n#### Required permissions\n\n- `write-orgs INFLUX_ORG_ID`\n\n*`INFLUX_ORG_ID`* is the ID of the organization that you want to\nremove an owner from.\n\n#### Related endpoints\n- [Authorizations](#tag/Authorizations-(API-tokens))\n"
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - in: path
        name: userID
        schema:
          type: string
        required: true
        description: The ID of the user to remove.
      - in: path
        name: orgID
        schema:
          type: string
        required: true
        description: 'The ID of the organization to remove an owner from.

          '
      responses:
        '204':
          description: 'Success.

            The user is no longer an owner of the organization.

            '
        '401':
          $ref: '#/components/responses/AuthorizationError'
        '404':
          $ref: '#/components/responses/ResourceNotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  responses:
    AuthorizationError:
      description: "Unauthorized. The error may indicate one of the following:\n\n  * The `Authorization: Token` header is missing or malformed.\n  * The API token value is missing from the header.\n  * The token doesn't have sufficient permissions to write to this organization and bucket.\n"
      content:
        application/json:
          schema:
            properties:
              code:
                description: 'The HTTP status code description. Default is `unauthorized`.

                  '
                readOnly: true
                type: string
                enum:
                - unauthorized
              message:
                readOnly: true
                description: A human-readable message that may contain detail about the error.
                type: string
          examples:
            tokenNotAuthorized:
              summary: Token is not authorized to access a resource
              value:
                code: unauthorized
                message: unauthorized access
    InternalServerError:
      description: 'Internal server error.

        The server encountered an unexpected situation.

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    GeneralServerError:
      description: Non 2XX error response from server.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ResourceNotFoundError:
      description: "Not found.\nA requested resource was not found.\nThe response body contains the requested resource type and the name value\n(if you passed it)--for example:\n\n- `\"organization name \\\"my-org\\\" not found\"`\n- `\"organization not found\"`: indicates you passed an ID that did not match\n   an organization.\n"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            org-not-found:
              summary: Organization name not found
              value:
                code: not found
                message: organization name "my-org" not found
            bucket-not-found:
              summary: Bucket name not found
              value:
                code: not found
                message: bucket "air_sensor" not found
            orgID-not-found:
              summary: Organization ID not found
              value:
                code: not found
                message: organization not found
    BadRequestError:
      description: 'Bad request.

        The response body contains detail about the error.


        #### InfluxDB OSS


        - Returns this error if an incorrect value is passed in the `org` parameter or `orgID` parameter.

        '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            orgProvidedNotFound:
              summary: The org or orgID passed doesn't own the token passed in the header
              value:
                code: invalid
                message: 'failed to decode request body: organization not found'
  schemas:
    PatchOrganizationRequest:
      type: object
      description: 'An object that contains updated organization properties to apply.

        '
      properties:
        name:
          type: string
          description: 'The name of the organization.

            '
        description:
          type: string
          description: 'The description of the organization.

            '
    AddResourceMemberRequestBody:
      type: object
      properties:
        id:
          type: string
          description: 'The ID of the user to add to the resource.

            '
        name:
          type: string
          description: 'The name of the user to add to the resource.

            '
      required:
      - id
    Link:
      type: string
      format: uri
      readOnly: true
      description: URI of resource.
    Links:
      type: object
      description: 'URI pointers for additional paged results.

        '
      properties:
        next:
          $ref: '#/components/schemas/Link'
        self:
          $ref: '#/components/schemas/Link'
        prev:
          $ref: '#/components/schemas/Link'
      required:
      - self
    ResourceMember:
      allOf:
      - $ref: '#/components/schemas/UserResponse'
      - type: object
        properties:
          role:
            type: string
            default: member
            enum:
            - member
    ResourceOwners:
      type: object
      properties:
        links:
          type: object
          properties:
            self:
              type: string
              format: uri
        users:
          type: array
          items:
            $ref: '#/components/schemas/ResourceOwner'
    UserResponse:
      properties:
        id:
          readOnly: true
          type: string
          description: 'The user ID.

            '
        name:
          type: string
          description: 'The user name.

            '
        status:
          description: 'The status of a user.

            An inactive user can''t read or write resources.

            '
          default: active
          type: string
          enum:
          - active
          - inactive
        links:
          type: object
          readOnly: true
          example:
            self: /api/v2/users/1
          properties:
            self:
              type: string
              format: uri
      required:
      - name
    Organizations:
      type: object
      properties:
        links:
          $ref: '#/components/schemas/Links'
        orgs:
          type: array
          items:
            $ref: '#/components/schemas/Organization'
    Organization:
      properties:
        links:
          type: object
          readOnly: true
          example:
            self: /api/v2/orgs/1
            members: /api/v2/orgs/1/members
            owners: /api/v2/orgs/1/owners
            labels: /api/v2/orgs/1/labels
            secrets: /api/v2/orgs/1/secrets
            buckets: /api/v2/buckets?org=myorg
            tasks: /api/v2/tasks?org=myorg
            dashboards: /api/v2/dashboards?org=myorg
          properties:
            self:
              $ref: '#/components/schemas/Link'
            members:
              $ref: '#/components/schemas/Link'
            owners:
              $ref: '#/components/schemas/Link'
            labels:
              $ref: '#/components/schemas/Link'
            secrets:
              $ref: '#/components/schemas/Link'
            buckets:
              $ref: '#/components/schemas/Link'
            tasks:
              $ref: '#/components/schemas/Link'
            dashboards:
              $ref: '#/components/schemas/Link'
        id:
          readOnly: true
          type: string
        name:
          type: string
        defaultStorageType:
          description: Discloses whether the organization uses TSM or IOx.
          type: string
          enum:
          - tsm
          - iox
        description:
          type: string
        createdAt:
          type: string
          format: date-time
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true
        status:
          description: If inactive, the organization is inactive.
          default: active
          type: string
          enum:
          - active
          - inactive
      required:
      - name
    ResourceOwner:
      allOf:
      - $ref: '#/components/schemas/UserResponse'
      - type: object
        properties:
          role:
            type: string
            default: owner
            enum:
            - owner
    PostOrganizationRequest:
      type: object
      properties:
        name:
          type: string
          description: 'The name of the organization.

            '
        description:
          type: string
          description: 'The description of the organization.

            '
      required:
      - name
    ResourceMembers:
      type: object
      properties:
        links:
          type: object
          properties:
            self:
              type: string
              format: uri
        users:
          type: array
          items:
            $ref: '#/components/schemas/ResourceMember'
    Error:
      properties:
        code:
          description: code is the machine-readable error code.
          readOnly: true
          type: string
          enum:
          - internal error
          - not implemented
          - not found
          - conflict
          - invalid
          - unprocessable entity
          - empty value
          - unavailable
          - forbidden
          - too many requests
          - unauthorized
          - method not allowed
          - request too large
          - unsupported media type
        message:
          readOnly: true
          description: Human-readable message.
          type: string
        op:
          readOnly: true
          description: Describes the logical code operation when the error occurred. Useful for debugging.
          type: string
        err:
          readOnly: true
          description: Stack of errors that occurred during processing of the request. Useful for debugging.
          type: string
      required:
      - code
  parameters:
    Limit:
      in: query
      name: limit
      required: false
      description: 'Limits the number of records returned. Default is `20`.

        '
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20
    Offset:
      in: query
      name: offset
      required: false
      description: 'The offset for pagination.

        The number of records to skip.


        For more information about pagination parameters, see [Pagination](https://docs.influxdata.com/influxdb/cloud/api/#tag/Pagination).

        '
      schema:
        type: integer
        minimum: 0
    TraceSpan:
      in: header
      name: Zap-Trace-Span
      description: OpenTracing span context
      example:
        trace_id: '1'
        span_id: '1'
        baggage:
          key: value
      required: false
      schema:
        type: string
    Descending:
      in: query
      name: descending
      required: false
      schema:
        type: boolean
        default: false
  securitySchemes:
    TokenAuthentication:
      type: apiKey
      name: Authorization
      in: header
      description: "Use the [Token authentication](#section/Authentication/TokenAuthentication)\nscheme to authenticate to the InfluxDB API.\n\nIn your API requests, send an `Authorization` header.\nFor the header value, provide the word `Token` followed by a space and an InfluxDB API token.\nThe word `Token` is case-sensitive.\n\n### Syntax\n\n`Authorization: Token INFLUX_API_TOKEN`\n\n### Example\n\n#### Use Token authentication with cURL\n\nThe following example shows how to use cURL to send an API request that uses Token authentication:\n\n```sh\ncurl --request GET \"INFLUX_URL/api/v2/buckets\" \\\n     --header \"Authorization: Token INFLUX_API_TOKEN\"\n```\n\nReplace the following:\n\n  - *`INFLUX_URL`*: your InfluxDB Cloud URL\n  - *`INFLUX_API_TOKEN`*: your [InfluxDB API token](https://docs.influxdata.com/influxdb/cloud/reference/glossary/#token)\n\n### Related endpoints\n\n- [`/authorizations` endpoints](#tag/Authorizations-(API-tokens))\n\n### Related guides\n\n- [Authorize API requests](https://docs.influxdata.com/influxdb/cloud/api-guide/api_intro/#authentication)\n- [Manage API tokens](https://docs.influxdata.com/influxdb/cloud/security/tokens/)\n"
    BasicAuthentication:
      type: http
      scheme: basic
      description: "### Basic authentication scheme\n\nUse the HTTP Basic authentication scheme for InfluxDB `/api/v2` API operations that support it:\n\n### Syntax\n\n`Authorization: Basic BASE64_ENCODED_CREDENTIALS`\n\nTo construct the `BASE64_ENCODED_CREDENTIALS`, combine the username and\nthe password with a colon (`USERNAME:PASSWORD`), and then encode the\nresulting string in [base64](https://developer.mozilla.org/en-US/docs/Glossary/Base64).\nMany HTTP clients encode the credentials for you before sending the\nrequest.\n\n_**Warning**: Base64-encoding can easily be reversed to obtain the original\nusername and password. It is used to keep the data intact and does not provide\nsecurity. You should always use HTTPS when authenticating or sending a request with\nsensitive information._\n\n### Examples\n\nIn the examples, replace the following:\n\n- **`EMAIL_ADDRESS`**: InfluxDB Cloud username (the email address the user signed up with)\n- **`PASSWORD`**: InfluxDB Cloud [API token](https://docs.influxdata.com/influxdb/cloud/reference/glossary/#token)\n- **`INFLUX_URL`**: your InfluxDB Cloud URL\n\n#### Encode credentials with cURL\n\nThe following example shows how to use cURL to send an API request that uses Basic authentication.\nWith the `--user` option, cURL encodes the credentials and passes them\nin the `Authorization: Basic` header.\n\n```sh\ncurl --get \"INFLUX_URL/api/v2/signin\"\n    --user \"EMAIL_ADDRESS\":\"PASSWORD\"\n```\n\n#### Encode credentials with Flux\n\nThe Flux [`http.basicAuth()` function](https://docs.influxdata.com/flux/v0.x/stdlib/http/basicauth/) returns a Base64-encoded\nbasic authentication header using a specified username and password combination.\n\n#### Encode credentials with JavaScript\n\nThe following example shows how to use the JavaScript `btoa()` function\nto create a Base64-encoded string:\n\n```js\nbtoa('EMAIL_ADDRESS:PASSWORD')\n```\n\nThe output is the following:\n\n```js\n'VVNFUk5BTUU6UEFTU1dPUkQ='\n```\n\nOnce you have the Base64-encoded credentials, you can pass them in the\n`Authorization` header--for example:\n\n```sh\ncurl --get \"INFLUX_URL/api/v2/signin\"\n    --header \"Authorization: Basic VVNFUk5BTUU6UEFTU1dPUkQ=\"\n```\n\nTo learn more about HTTP authentication, see\n[Mozilla Developer Network (MDN) Web Docs, HTTP authentication](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication)._\n"
x-tagGroups:
- name: Overview
  tags:
  - Quick start
  - Authentication
  - Supported operations
  - Headers
  - Pagination
  - Response codes
- name: Popular endpoints
  tags:
  - Data I/O endpoints
  - Security and access endpoints
  - System information endpoints
- name: All endpoints
  tags: []
